---
driver:
  name: terraform
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      controls:
        - instance_state

platforms:
  - name: terraform

suites:
  - name: default